# Change these first
owner: puro-earth # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

assignees:
  - mathewrapid

sites:
  - name: Puro.earth
    url: https://puro.earth
  - name: Puro.earth Registry
    url: https://registry.puro.earth
    assignees:
      - tlehtola
      - ksaren
  - name: Puro.earth Registry back-end
    url: $REGISTRY_BACKEND
    assignees:
      - tlehtola
      - ksaren
  - name: Puro.earth Portal
    url: https://my.puro.earth/
    assignees:
      - KimmoM-Sprintit
  - name: Puro.earth Registry Services API
    url: https://rs.api.puro.earth/$API_SERVICES_HEALT_ENDPOINT
    assignees:
      - tlehtola
      - ksaren
  - name: Puro.earth Sales Channel Management Services API
    url: https://scms.api.puro.earth/$API_SERVICES_HEALT_ENDPOINT
    assignees:
      - tlehtola
      - ksaren
  - name: Puro.earth Sales Channel Services API
    url: https://scs.api.puro.earth/$API_SERVICES_HEALT_ENDPOINT
    assignees:
      - tlehtola
      - ksaren
  - name: Puro.earth Sales Channel Services API Documentation
    url: https://docs.api.puro.earth/
    assignees:
      - tlehtola
      - ksaren

status-website:
  favicon: https://raw.githubusercontent.com/puro-earth/status/master/assets/puro_favicon.png
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.purosandbox.com
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/puro-earth/status/master/assets/puro_logo.svg
  name: Puro.earth
  introTitle: "**Puro.earth** status page."
  introMessage: This is Puro.earth's status page.
  navbar:
    - title: Status
      href: /
    - title: Puro.earth
      href: https://puro.earth

i18n:
  footer: This page is open source, powered by [Upptime](https://upptime.js.org)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
