# Change these first
owner: puro-earth # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

assignees:
  - villetou

sites:
  - name: Puro.earth
    url: https://puro.earth
    assignees:
      - kushpuroearth
  - name: Puro.earth Registry
    url: https://registry.puro.earth
    assignees:
      - villetou
  - name: Puro.earth Portal 1.0
    url: https://my.puro.earth/
    assignees:
      - kushpuroearth
  - name: Puro.earth dMRV API
    url: https://api.portal.puro.earth/health
    assignees:
      - villetou
  - name: Puro.earth API Documentation
    url: https://docs.api.puro.earth/
    assignees:
      - villetou

status-website:
  favicon: https://raw.githubusercontent.com/puro-earth/status/master/assets/puro_favicon.png
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.purosandbox.com
  # baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/puro-earth/status/master/assets/puro_logo.svg
  name: Puro.earth
  introTitle: "**Puro.earth** status page."
  introMessage: This is Puro.earth's status page.
  navbar:
    - title: Status
      href: /
    - title: Puro.earth
      href: https://puro.earth

i18n:
  footer: This page is open source, powered by [Upptime](https://upptime.js.org)

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
